### PR TITLE
Update README for MacOS users

### PR DESCRIPTION
**Pull request by nguterresn**
First of all, thanks for this amazing tutorial on how to make this work on VSCode; it makes my life better.

As a way of bringing some love to the project here is my contribution. Let me me know if you find this useful, if not just discard.

### CODE REVIEW

**Comment by nguterresn** [comment]
Haven't test it but can't see what wouldn't work on Windows.

**Comment by MaJerle** [comment]
Tested just now. If I add `"serverArgs": ["-m", "1", "-k", "-l", "1", "-s"],` to the launch.json file, I get an error initializing ST-Link.

Full launch file:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Microcontroller - ST-Link",
            "cwd": "${workspaceFolder}",
            "type": "cortex-debug",
            "executable": "${command:cmake.launchTargetPath}", //or fixed file path: build/stm32h735g-dk-led.elf
            "request": "launch",                //Use "attach" to connect to target w/o elf download
            "servertype": "stlink",
            "device": "",                       //MCU used, ex. "STM32H735IG"
            "interface": "swd",
            "serialNumber": "0026001A3438510934313939",                 //Set ST-Link ID if you use multiple at the same time
            "runToEntryPoint": "main",
            "svdFile": "${workspaceFolder}/../../svd/STM32H723.svd",      //Path to SVD file to see registers
            "v1": false,
            "showDevDebugOutput": "both",
            "serverArgs": ["-m", "1", "-k", "-l", "1", "-s"],
        }
    ]
}
```

Terminal message
```
STMicroelectronics ST-LINK GDB server. Version 7.3.0
Copyright (c) 2023, STMicroelectronics. All rights reserved.

Starting server with the following options:
        Persistent Mode            : Disabled
        Logging Level              : 1
        Listen Port Number         : 50000
        Status Refresh Delay       : 15s
        Verbose Mode               : Disabled
        SWD Debug                  : Enabled
        InitWhile                  : Enabled

Target not halted after reset.
Target not halted

Error in initializing ST-LINK device.
Reason: Target not halted.
```

**Comment by nguterresn** [comment]
Ah I see. Maybe this only works when using a STM32 NUCLEO dev board? :)
I'm not entirely sure, but I could only make it work with those arguments, specially the `-m 1`.

**Comment by MaJerle** [comment]
As per ST-Link GDB server recommendations, `-m x` shall be used for multi-core only. Which STM32 are you trying with?

**Comment by nguterresn** [comment]
I'm using the [STM32H5](https://www.st.com/en/evaluation-tools/nucleo-h563zi.html).

**Comment by MaJerle** [comment]
And if you add `-m 0` it doesn't work?

**Comment by nguterresn** [comment]
It doesn't work.

```md
[2023-06-26T11:52:06.290Z] SERVER CONSOLE DEBUG: onBackendConnect: gdb-server session connected. You can switch to "DEBUG CONSOLE" to see GDB interactions.
/Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.stlink-gdb-server.macos64_2.0.500.202301161003/tools/bin/ST-LINK_gdbserver -p 50000 -cp /Applications/STM32CubeIDE.app/Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.cubeprogrammer.macos64_2.0.600.202301161003/tools/bin --swd --halt -m 0 -k -l 1 -s


STMicroelectronics ST-LINK GDB server. Version 7.3.0
Copyright (c) 2023, STMicroelectronics. All rights reserved.

Starting server with the following options:
        Persistent Mode            : Disabled
        Logging Level              : 1
        Listen Port Number         : 50000
        Status Refresh Delay       : 15s
        Verbose Mode               : Disabled
        SWD Debug                  : Enabled
        InitWhile                  : Enabled

Target unknown error 32

Error in initializing ST-LINK device.
Reason: Unknown. Please check power and cabling to target.
[2023-06-26T11:52:06.652Z] SERVER CONSOLE DEBUG: onBackendConnect: gdb-server session closed
GDB server session ended. This terminal will be reused, waiting for next session to start...
```

**Comment by nguterresn** [comment]
@MaJerle You need any updates on this? Otherwise, just close it.

**Comment by MaJerle** [comment]
This seems to apply only for H5. So better we update the docs and indicate this as a "troubleshooting" instead.

Can you update pull request and I merge?

**Pull request closed without merging**
